name: ci-cd
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Build typescript
        run: npm run build -- --noEmit

      - name: Run Lint
        run: npm run lint

      - name: Run tests and instrument coverage
        run: npm run test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 944bb86ef4c84643b0711f0592ce7597c3e195e38c84e57888136ca2c850312f
        with:
          debug: true
