name: ci-cd
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_TEST_USERNAME: ${{ secrets.DB_USER }}
      DB_TEST_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_TEST_NAME: ${{ secrets.DB_NAME }}
      DB_TEST_HOST: ${{ secrets.DB_HOST }}
      JWT_SECRET: 3WJWcULn72ea&a42
      JWT_EXPIRES_IN: 8h
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          # coverageCommand: npm run test
          debug: true
