name: ci-cd
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      # - name: Run Tests
      #   run: npm run test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 944bb86ef4c84643b0711f0592ce7597c3e195e38c84e57888136ca2c850312f
        with:
          coverageCommand: npm run test
          debug: true

